### ISSUE TITLE
Couldn't find a valid ICU (Linux vs. dotnet)

### ISSUE THREAD

**Issue by mwalzer** [PaulBrack/Yamato#111]
You can expect an error like this if you have a run-off-the-mill linux system without the dependencies resolved for dotnet
```
Yamato.Console -i /home/walzer/Downloads/collinsb_I180316_005_SW-A.mzML 
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
Aborted (core dumped)
```

**Comment by mwalzer** [comment]
This is to be expected. For future reference here are some common requirements:
* set %environment DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
* install libunwind
* install icu-libs
