### ISSUE TITLE
Trouble generating report file

### ISSUE THREAD

**Issue by mwalzer** [PaulBrack/Yamato#163]
I finally got the chance to try out the release (v1) on some PRIDE dataset files. What I did is basically this:
```
SwaMe.Console -i /hps/nobackup2/proteomics/SwathMSdata/nf_pride_test/test_PXD005661_bobbytailored/work/ea/3c6e09ab912451efeb6779fdeffc74/150307_P17458_Group4_IDA_1.mzML -out 150307_P17458_Group4_IDA_1.swame.out -r SwathMSdata/ion_libraries/irt.swame.tsv 
```
Which resulted in:
```
Unhandled exception. System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.AddWithResize(T item)
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean threading, Boolean irt)
   at MzmlParser.MzmlReader.<>c__DisplayClass37_0.<ReadSpectrum>b__1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```
Where I figured I might need to employ the `-z` flag which helped along, but 
```
2020-05-22 14:19:48.0629|INFO|Yamato.Console.Program|Loading file: /hps/nobackup2/proteomics/SwathMSdata/nf_pride_test/test_PXD005661_bobbytailored/work/ea/3c6e09ab912451efeb6779fdeffc74/150307_P17458_Group4_IDA_1.mzML
2020-05-22 14:19:48.1130|INFO|LibraryParser.SVReader|Loading file: SwathMSdata/ion_libraries/irt.swame.tsv
Unhandled exception.Unhandled exception.Unhandled exception.   Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception.Unhandled exception.  Unhandled exception. Unhandled exception.Unhandled exception.  Unhandled exception.Unhandled exception.  Unhandled exception.Unhandled exception.  Unhandled exception. Unhandled exception. Unhandled exception.Unhandled exception.  Unhandled exception.Unhandled exception.Unhandled exception.  Unhandled exception.  Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. System.IO.IOException: The process cannot access the file '/tmp/34218cee-38c8-45f1-879b-ab52cf8cf818/Yamato_2_1_0.tempscan' because it is being used by another process.
```
Made me guess I need to deactivate the threads with `-t false` and for the 'standard' files (i.e. the navarro data) this would have been it. But for that particular data I then got 
```
2020-05-22 14:37:59.1735|WARN|MzmlParser.MzmlReader|Total Ion Current value was not found and had to be calculated from the spectra. This will cause this value to be incorrect for centroided MZML files, peak picked data, or other manipulated spectra.
2020-05-22 14:37:59.1739|INFO|Yamato.Console.Program|Generating metrics...
2020-05-22 14:38:01.6005|ERROR|SwaMe.MetricGenerator|(IsolationWindowUpperOffset {0} or IsolationWindowLowerOffset {0} for the one of the scans has not been changed from default value. swathSizeDifference is therefore zero, 100000, 100000)
2020-05-22 14:38:01.8290|FATAL|Yamato.Console.Program|An unexpected error occured
```
I tried the `-m` parameter but that didn't help. Does it mean my input is faulty? 
As mentioned works fine with other, more tested, data. *But* the output file wasn't called as I expected
called `napedro_L120224_009_SW.out` but `ut`. Is it because of the `.out` or is '-o' supposed to be a directory? (Might be a different issue after all.)

**Comment by mwalzer** [comment]
@PaulBrack The issue title is not very specific, I know, please rename as you see fit

**Comment by Ozzard** [comment]
Thanks, @mwalzer.  I can help with at least one of the mysteries there: `-out` is not a valid parameter, but `-o` is.  So the command-line parser (we use a standard one that supposedly emulates GNU getopt, though I'm a little unconvinced) interpreted that as `-o ut` and created the output file `ut` as a result.

**Comment by PaulBrack** [comment]
Hi Mathias - can you let me know where you're at with this one? Did Peter's suggestion resolve your issue?

**Comment by mwalzer** [comment]
Thanks for coming back on that, Paul.
> resolve your issue?

Unfortunately, not completely, no. 
Though @Ozzard was quick to spot my -o/-out mistake and I now have properly named output, thanks for that.
There is still 
```
2020-05-22 14:37:59.1735|WARN|MzmlParser.MzmlReader|Total Ion Current value was not found and had to be calculated from the spectra. This will cause this value to be incorrect for centroided MZML files, peak picked data, or other manipulated spectra.
2020-05-22 14:37:59.1739|INFO|Yamato.Console.Program|Generating metrics...
2020-05-22 14:38:01.6005|ERROR|SwaMe.MetricGenerator|(IsolationWindowUpperOffset {0} or IsolationWindowLowerOffset {0} for the one of the scans has not been changed from default value. swathSizeDifference is therefore zero, 100000, 100000)
2020-05-22 14:38:01.8290|FATAL|Yamato.Console.Program|An unexpected error occured
```
And I don't know if my data is semi-faulty. Semi, because FileInfo and other tools don't complain, but  that doesn't have to mean much.

**Comment by PaulBrack** [comment]
Hi Mathias, can you provide more replication info - the stack trace, full command line and input file please

**Comment by mwalzer** [comment]
Sure, but as I said, it is quite likely that there is nothing wrong with swame, but it is because the input data is insufficient. Yet, it would be awesome if swame could check if the data it gets is 'analysis-ready' or what is missing. 

So the file (150307_P17458_Group4_IDA_1.mzML) came out of PXD005661 converteed with the sciex converter as we know it. And this was the complete commandline interaction, can't give you a stack trace though, I have no clue how to get that info out of a c# application:
```
SwaMe.Console -i /hps/nobackup2/proteomics/SwathMSdata/nf_pride_test/test_PXD005661_bobbytailored/work/ea/3c6e09ab912451efeb6779fdeffc74/150307_P17458_Group4_IDA_1.mzML -o 150307_P17458_Group4_IDA_1.swame.out -r /hps/nobackup2/proteomics/SwathMSdata/ion_libraries/irt.swame.tsv -m 0.5
2020-06-03 17:51:42.7222|INFO|Yamato.Console.Program|Loading file: /hps/nobackup2/proteomics/SwathMSdata/nf_pride_test/test_PXD005661_bobbytailored/work/ea/3c6e09ab912451efeb6779fdeffc74/150307_P17458_Group4_IDA_1.mzML
2020-06-03 17:51:42.7741|INFO|LibraryParser.SVReader|Loading file: /hps/nobackup2/proteomics/SwathMSdata/ion_libraries/irt.swame.tsv
2020-06-03 17:51:42.8950|INFO|MzmlParser.MzmlReader|0 MS2 scans read
2020-06-03 17:51:42.8950|INFO|MzmlParser.MzmlReader|0 MS2 scans read
2020-06-03 17:51:42.8950|INFO|MzmlParser.MzmlReader|0 MS2 scans read
2020-06-03 17:51:46.4297|INFO|MzmlParser.MzmlReader|10000 MS2 scans read
2020-06-03 17:51:46.4317|INFO|MzmlParser.MzmlReader|10000 MS2 scans read
2020-06-03 17:51:46.4326|INFO|MzmlParser.MzmlReader|10000 MS2 scans read
2020-06-03 17:51:49.6401|INFO|MzmlParser.MzmlReader|20000 MS2 scans read
2020-06-03 17:51:49.6401|INFO|MzmlParser.MzmlReader|20000 MS2 scans read
2020-06-03 17:51:49.6409|INFO|MzmlParser.MzmlReader|20000 MS2 scans read
2020-06-03 17:51:53.5445|INFO|MzmlParser.MzmlReader|30000 MS2 scans read
2020-06-03 17:52:01.5495|INFO|MzmlParser.MzmlReader|40000 MS2 scans read
2020-06-03 17:52:12.2983|INFO|MzmlParser.MzmlReader|50000 MS2 scans read
2020-06-03 17:52:17.7279|INFO|MzmlParser.MzmlReader|60000 MS2 scans read
2020-06-03 17:52:24.0201|INFO|MzmlParser.MzmlReader|70000 MS2 scans read
2020-06-03 17:52:27.9295|INFO|MzmlParser.MzmlReader|80000 MS2 scans read
2020-06-03 17:52:29.3446|INFO|MzmlParser.MzmlReader|90000 MS2 scans read
2020-06-03 17:52:30.6475|INFO|MzmlParser.MzmlReader|100000 MS2 scans read
2020-06-03 17:52:32.0385|INFO|MzmlParser.MzmlReader|110000 MS2 scans read
2020-06-03 17:52:32.0388|INFO|MzmlParser.MzmlReader|110000 MS2 scans read
2020-06-03 17:52:33.9031|INFO|MzmlParser.MzmlReader|Finding base peak spectra...
2020-06-03 17:52:40.9447|INFO|MzmlParser.MzmlReader|Selecting best IRT peptide candidates...
2020-06-03 17:52:41.4722|WARN|MzmlParser.MzmlReader|Total Ion Current value was not found and had to be calculated from the spectra. This will cause this value to be incorrect for centroided MZML files, peak picked data, or other manipulated spectra.
2020-06-03 17:52:41.4728|INFO|Yamato.Console.Program|Generating metrics...
2020-06-03 17:52:43.4177|ERROR|SwaMe.MetricGenerator|(IsolationWindowUpperOffset {0} or IsolationWindowLowerOffset {0} for the one of the scans has not been changed from default value. swathSizeDifference is therefore zero, 100000, 100000)
2020-06-03 17:52:43.6245|FATAL|Yamato.Console.Program|An unexpected error occured
```

**Comment by mwalzer** [comment]
mzQC getting written now, closing
