### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException: Value cannot be null. 

### ISSUE THREAD

**Issue by mwalzer** [PaulBrack/Yamato#81]
No idea what could be causing this. 
```
2019-11-28 16:01:22.9327|INFO|Yamato.Console.Program|Loading file: collinsb_I180316_005_SW-A.mzML

Unhandled Exception:Unhandled Exception:
Unhandled Exception:
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in C:\Sandbox\github\Yamato\MzmlReader\MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted 
```

**Comment by mwalzer** [comment]
As requested, here the spectrum grep for various files tested
```
$ grep 'spectrum' napedro_L120420_010_SW.mzML | head -n 10
      <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
$ grep 'spectrum' napedro_L120228_007_SW.mzML | head -n 10
      <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
$ grep 'spectrum' napedro_L120224_001_SW.mzML | head -n 10
      <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
      <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
      <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" />
$ grep 'spectrum' ../../../collinsb_I180316_005_SW-A.mzML | head -n 10
			<cvParam cvRef="MS" accession="MS:1000294" name="mass spectrum" />
			<cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
				<cvParam cvRef="MS" accession="MS:1000777" name="spectrum identifier nativeID format" />
		<spectrumList count="81705" defaultDataProcessingRef="dp_sp_0">
			<spectrum id="scan=1" index="0" defaultArrayLength="0" dataProcessingRef="dp_sp_0">
				<cvParam cvRef="MS" accession="MS:1000525" name="spectrum representation" />
				<cvParam cvRef="MS" accession="MS:1000294" name="mass spectrum" />
			</spectrum>
			<spectrum id="scan=2" index="1" defaultArrayLength="0">
				<cvParam cvRef="MS" accession="MS:1000525" name="spectrum representation" />
                                                      
$ grep 'spectrum' ../../../split_napedro_L120420_010_SW-400AQUA__human_2ul_dilution_1_1.nf.pp.mzML | head -n 10
			<cvParam cvRef="MS" accession="MS:1000582" name="SIM spectrum" />
				<cvParam cvRef="MS" accession="MS:1000777" name="spectrum identifier nativeID format" />
		<spectrumList count="2373" defaultDataProcessingRef="dp_sp_0">
			<spectrum id="scan=1" index="0" defaultArrayLength="50" dataProcessingRef="dp_sp_0">
				<cvParam cvRef="MS" accession="MS:1000127" name="centroid spectrum" />
				<cvParam cvRef="MS" accession="MS:1000582" name="SIM spectrum" />
			</spectrum>
			<spectrum id="scan=2" index="1" defaultArrayLength="41">
				<cvParam cvRef="MS" accession="MS:1000127" name="centroid spectrum" />
				<cvParam cvRef="MS" accession="MS:1000582" name="SIM spectrum" />

```

**Comment by mwalzer** [comment]
The new standalone build yields a different error:
```
Yamato.Console -i collinsb_I180316_005_SW-A.mzML
2019-12-04 11:41:29.9106|INFO|Yamato.Console.Program|Verbose output selected: enabled logging for all levels
2019-12-04 11:41:29.9402|INFO|Yamato.Console.Program|Loading file: collinsb_I180316_005_SW-A.mzML






Unhandled Exception:Unhandled Exception:Unhandled Exception:Unhandled Exception: Unhandled Exception:    
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception:
 Unhandled Exception: Unhandled Exception:
 Unhandled Exception: 
Unhandled Exception: 

Unhandled Exception:
Unhandled Exception:  Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 


Unhandled Exception: Unhandled Exception:Unhandled Exception:
  Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 487
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 324
   at MzmlParser.MzmlReader.<>c__DisplayClass25_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlReader/MzmlReader.cs:line 240
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

**Comment by PaulBrack** [comment]
The reader isn't checking for empty spectra - will implement a check

**Comment by mwalzer** [comment]
back to initial situation in `v1.0.0-b`

**Comment by PaulBrack** [comment]
Fixed

https://github.com/PaulBrack/Yamato/commit/e8d88741f215a7f38c13fe3bbf74bfc674555aa5
